member:
  id: 1
  account: admin
  remark: admin
#spring:
#  profiles:
#    active: dev
server:
  port: 8081
---
spring:
  profiles: dev
server:
  port: 8084
---
spring:
  profiles: prod
server:
  port: 8083